#!/usr/bin/env node
// Snapshots Chainlink's public directory of Robinhood Chain MAINNET feeds into
// sdk/src/chainlinkFeeds.ts, so every tokenized stock / bond / crypto feed has
// a symbol + class in the SDK (titles, icons, market templates). Re-run when
// Chainlink lists new feeds:  pnpm --filter @novakoracle/sdk gen:feeds
// (The frontend's /api/feeds route still reads the directory + prices live.)
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DIRECTORY = "https://reference-data-directory.vercel.app/feeds-robinhood-mainnet.json";
const BOND_ETFS = new Set(["SGOV", "SHY", "BND", "TLT", "IEF", "BIL", "AGG", "GOVT"]);

const res = await fetch(DIRECTORY);
if (!res.ok) throw new Error(`directory HTTP ${res.status}`);
const feeds = (await res.json())
  .filter((f) => f.proxyAddress && !/exchange rate/i.test(f.name))
  .map((f) => {
    const symbol = (f.docs?.baseAsset ?? f.name.replace(/^Robinhood /, "").split(/[ /-]/)[0]).toUpperCase();
    const assetClass = BOND_ETFS.has(symbol) ? "Bond" : f.docs?.assetClass === "Equity" ? "Equity" : "Crypto";
    return {
      symbol,
      name: (f.assetName || (symbol === "SGOV" ? "iShares 0-3 Month Treasury Bond ETF" : f.name)).replace(" (Robinhood Tokenized Equity)", ""),
      assetClass,
      address: f.proxyAddress,
      decimals: f.decimals,
      marketHours: f.docs?.marketHours ?? null,
    };
  })
  .sort((a, b) => a.symbol.localeCompare(b.symbol));

const out = `// AUTO-GENERATED by sdk/scripts/gen-feeds.mjs from Chainlink's directory
// (${DIRECTORY}) — do not edit by hand.
// Snapshot: ${new Date().toISOString().slice(0, 10)}, ${feeds.length} feeds on Robinhood Chain mainnet.

export type FeedAssetClass = "Equity" | "Bond" | "Crypto";

export interface ChainlinkFeedInfo {
  symbol: string;
  name: string;
  assetClass: FeedAssetClass;
  address: \`0x\${string}\`;
  decimals: number;
  marketHours: string | null;
}

export const CHAINLINK_FEED_CATALOG: ChainlinkFeedInfo[] = ${JSON.stringify(feeds, null, 2)};

/** Look up a feed by proxy address (case-insensitive). */
export function feedByAddress(address: string): ChainlinkFeedInfo | undefined {
  const a = address.toLowerCase();
  return CHAINLINK_FEED_CATALOG.find((f) => f.address.toLowerCase() === a);
}

/** Look up a feed by ticker symbol, e.g. "NVDA", "SGOV", "ETH". */
export function feedBySymbol(symbol: string): ChainlinkFeedInfo | undefined {
  const s = symbol.toUpperCase();
  return CHAINLINK_FEED_CATALOG.find((f) => f.symbol === s);
}
`;
const target = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "chainlinkFeeds.ts");
writeFileSync(target, out);
console.log(`wrote ${feeds.length} feeds -> ${target}`);
