#!/usr/bin/env node
// Generates sdk/src/abis.ts from Foundry build output (run `forge build`
// first) and sdk/src/deployments.ts from deployments/<chainId>.json (written
// by script/export-deployment.mjs). Replaces the old hand-maintained ABIs so
// contract changes can't silently drift from the SDK.
//
// Usage: pnpm --filter @novak/sdk gen

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const sdkRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(sdkRoot, "..");

const contracts = [
  ["EventRegistry", "eventRegistryAbi"],
  ["DisputeManager", "disputeManagerAbi"],
  ["EventComposer", "eventComposerAbi"],
  ["EventBus", "eventBusAbi"],
  ["SubscriptionManager", "subscriptionManagerAbi"],
  ["Settlement", "settlementAbi"],
  ["PositionManager", "positionManagerAbi"],
  ["Market", "marketAbi"],
  ["StockLendingGuard", "stockLendingGuardAbi"],
  ["MockUSDG", "mockUsdgAbi"],
];

const header = `// AUTO-GENERATED by sdk/scripts/gen.mjs from Foundry build output — do not
// edit by hand. Regenerate with: forge build && pnpm --filter @novak/sdk gen
`;

let abis = header;
for (const [name, exportName] of contracts) {
  const artifact = join(repoRoot, "out", `${name}.sol`, `${name}.json`);
  if (!existsSync(artifact)) {
    console.error(`missing ${artifact} — run \`forge build\` first`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
  abis += `\nexport const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(join(sdkRoot, "src", "abis.ts"), abis);

const depDir = join(repoRoot, "deployments");
const deployments = {};
if (existsSync(depDir)) {
  for (const f of readdirSync(depDir).filter((f) => f.endsWith(".json"))) {
    const d = JSON.parse(readFileSync(join(depDir, f), "utf8"));
    deployments[d.chainId] = d;
  }
}
const depTs = `${header}
import type { NovakDeployment } from "./types.js";

/** Known deployments keyed by chain ID (46630 = Robinhood Chain testnet, 31337 = local anvil). */
export const deployments: Record<number, NovakDeployment> = ${JSON.stringify(deployments, null, 2)};
`;
writeFileSync(join(sdkRoot, "src", "deployments.ts"), depTs);

console.log(
  `generated ${contracts.length} ABIs; deployments for chain(s): ${Object.keys(deployments).join(", ") || "none"}`,
);
