// AUTO-GENERATED by sdk/scripts/gen-feeds.mjs from Chainlink's directory
// (https://reference-data-directory.vercel.app/feeds-robinhood-mainnet.json) — do not edit by hand.
// Snapshot: 2026-10-04, 53 feeds on Robinhood Chain mainnet.

export type FeedAssetClass = "Equity" | "Bond" | "Crypto";

export interface ChainlinkFeedInfo {
  symbol: string;
  name: string;
  assetClass: FeedAssetClass;
  address: `0x${string}`;
  decimals: number;
  marketHours: string | null;
}

export const CHAINLINK_FEED_CATALOG: ChainlinkFeedInfo[] = [
  {
    "symbol": "AAPL",
    "name": "Apple",
    "assetClass": "Equity",
    "address": "0x6B22A786bAa607d76728168703a39Ea9C99f2cD0",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "AMD",
    "name": "Advanced Micro Devices / AMD",
    "assetClass": "Equity",
    "address": "0x943A29E7ae51A4798823ca9eEd2ed533B2A22C72",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "AMZN",
    "name": "Amazon",
    "assetClass": "Equity",
    "address": "0xD5a1508ceD74c084eBf3cBe853e2C968fB2a651C",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "ASML",
    "name": "ASML Holding NV (Nasdaq)",
    "assetClass": "Equity",
    "address": "0xB4106147E8cce40b7d46124090d373A71b70f87D",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "BABA",
    "name": "Alibaba Group Holding Ltd (ADRs)",
    "assetClass": "Equity",
    "address": "0x62Cc8F9b5f56a33c9C8A60c8B92779f523c4E984",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "BTC",
    "name": "Bitcoin",
    "assetClass": "Crypto",
    "address": "0xa2c5184bF03d373Dc9dE4876eb4Bce595B460251",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "BTC.B",
    "name": "Avalanche Bridged BTC",
    "assetClass": "Crypto",
    "address": "0x5BB5e6a17a477d5B6Fec77b4322daD4A66bFb732",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "CBBTC",
    "name": "Coinbase Wrapped BTC",
    "assetClass": "Crypto",
    "address": "0x0009cD492adf8167f9eEBf1293556A673530a21a",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "CLSK",
    "name": "CleanSpark Inc",
    "assetClass": "Equity",
    "address": "0x810c12D3a554Bc47fd39597Fe3b3AAC4941F50eF",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "COIN",
    "name": "Coinbase",
    "assetClass": "Equity",
    "address": "0xA3a468A452940B7D6b69991207B508c609a98Ef2",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "CRCL",
    "name": "Circle Internet Group Inc",
    "assetClass": "Equity",
    "address": "0x6652eDf64bA3731C4F2D3ce821A0Fb1f1f6b482a",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "CRWV",
    "name": "CoreWeave Inc",
    "assetClass": "Equity",
    "address": "0xe1b3aABCAFAd1c94708dc1367dcfF8Aa4407487C",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "ENA",
    "name": "Ethena",
    "assetClass": "Crypto",
    "address": "0x2A291496b3aa19d8948e442Ef28Ee952f3Ee97E8",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "ETH",
    "name": "Ethereum",
    "assetClass": "Crypto",
    "address": "0x78F3556b67E17Df817D51Ef5a990cDaF09E8d3A9",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "EURC",
    "name": "Euro Coin",
    "assetClass": "Crypto",
    "address": "0xfF2B10c1973eD10c841434f98e456d8f3a0D7DD8",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "EWY",
    "name": "ISHARES MSCI SOUTH KOREA ETF (Robinhood Tokenized ETF)",
    "assetClass": "Equity",
    "address": "0xEFdf54610B62A7753Ec30bDc380847c12D32e1D1",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "GLD",
    "name": "SPDR Gold Shares • Robinhood Token",
    "assetClass": "Crypto",
    "address": "0x470A51258068043bd43dC0a56245625C9fE86eB0",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "GME",
    "name": "Gamestop",
    "assetClass": "Equity",
    "address": "0x27C71df6A64fB476468EdF256CF72c038baB5B67",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "GOOGL",
    "name": "Alphabet",
    "assetClass": "Equity",
    "address": "0xF6f373a037c30F0e5010d854385cA89185AE638b",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "INTC",
    "name": "Intel Corp",
    "assetClass": "Equity",
    "address": "0x3f390C5C24628Ac7C489515402235FeAD71D1913",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "IONQ",
    "name": "IonQ, Inc.",
    "assetClass": "Equity",
    "address": "0x22EfeC4919baf55F360E0EDee4AbEB26DE4971eb",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "LBTC",
    "name": "LOMBARD STAKED BTC",
    "assetClass": "Crypto",
    "address": "0xa621344AdAEE699491597Fd8890E0C59a5BFBE59",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "LINK",
    "name": "Chainlink",
    "assetClass": "Crypto",
    "address": "0xe86e3422Aa9B5e8ee9f3E41a63975bC387A8bce9",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "META",
    "name": "Meta",
    "assetClass": "Equity",
    "address": "0x7C38C00C30BEe9378381E7B6135d7283356D71b1",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "MSFT",
    "name": "Microsoft",
    "assetClass": "Equity",
    "address": "0x45C3C877C15E6BA2EBB19eA114Ea508d14C1Af2E",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "MSTR",
    "name": "Microstrategy Inc Class A (Robinhood Tokenized Equity",
    "assetClass": "Equity",
    "address": "0x396118bdFB181e6240E74D243F266B061c0edc3D",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "MU",
    "name": "Micron Technology Inc",
    "assetClass": "Equity",
    "address": "0x425EEFdCf05ed6526C3cE61Af99429A228a6d596",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "NBIS",
    "name": "Nebius Group",
    "assetClass": "Equity",
    "address": "0xE1D87B116Ba0fe898998f1D140339D1fA1E09705",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "NVDA",
    "name": "Nvidia",
    "assetClass": "Equity",
    "address": "0x379EC4f7C378F34a1B47E4F3cbeBCbAC3E8E9F15",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "ORCL",
    "name": "Oracle Corp",
    "assetClass": "Equity",
    "address": "0x0e6a64a2B58A6693a531E6c555f3A5d042eEA844",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "PLTR",
    "name": "Palantir Technologies Inc",
    "assetClass": "Equity",
    "address": "0x820ABedFF239034956B7A9d2F0a331f9F075eB4c",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "QQQ",
    "name": "Invesco QQQ (Robinhood Tokenized ETF)",
    "assetClass": "Equity",
    "address": "0x80901d846d5D7B030F26B480776EE3b29374C2ae",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "RGTI",
    "name": "Rigetti Computing Inc",
    "assetClass": "Equity",
    "address": "0x2A045cF1C49c61c166C036d2f06FA2D2d984f765",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "RHDELL",
    "name": "Dell Technologies Inc",
    "assetClass": "Equity",
    "address": "0x1C6c8cADBe02E19129c39dDB92281cE4c0bf206b",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "RKLB",
    "name": "Rocket Lab Corp",
    "assetClass": "Equity",
    "address": "0x045477BF65Aef6f4F2386ad0164579e48381CC74",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "SGOV",
    "name": "iShares 0-3 Month Treasury Bond ETF",
    "assetClass": "Bond",
    "address": "0xa0DF4ee0fFf975306345875E3548Fcc519577A11",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "SLV",
    "name": "iShares Silver Trust ETF (Robinhood Tokenized ETF)",
    "assetClass": "Equity",
    "address": "0x209b73908e92Ae021826eD79609845451Ecba2ce",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "SNDK",
    "name": "SanDisk Corp",
    "assetClass": "Equity",
    "address": "0xfb133Fa4B7b385802B693a293606682Df47109A3",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "SPCX",
    "name": "Space Exploration Technologies Corp.",
    "assetClass": "Equity",
    "address": "0xB265810950ba6c5C0Ff821c9963014a56fD8Bffb",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "SPY",
    "name": "State Street SPDR S&P 500 ETF Trust (Robinhood Tokenized ETF)",
    "assetClass": "Equity",
    "address": "0x319724394D3A0e3669269846abE664Cd621f9f6A",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "SYRUPUSDC",
    "name": "Syrup USDC",
    "assetClass": "Crypto",
    "address": "0x8765c3B9Cda41d1029E780D0c1C37C8200DC4675",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "TSLA",
    "name": "Tesla",
    "assetClass": "Equity",
    "address": "0x4A1166a659A55625345e9515b32adECea5547C38",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "TSM",
    "name": "Taiwan Semiconductor",
    "assetClass": "Equity",
    "address": "0x874cF94aa8eC88Fd9560094dD065f2fB3E41Fc2F",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "USAR",
    "name": "Robinhood USAR-USD",
    "assetClass": "Crypto",
    "address": "0xA994d3684e8400A6c8078226925779FdeE682DD9",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "USDC",
    "name": "USD Coin",
    "assetClass": "Crypto",
    "address": "0x9e6f4605992a899eE2999999F3Ec80C41F452546",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "USDE",
    "name": "Ethena USDe",
    "assetClass": "Crypto",
    "address": "0xb9fB4e65744E4178894f7C61CF80E8a48A5f224a",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "USDG",
    "name": "Global Dollar",
    "assetClass": "Crypto",
    "address": "0x61B7e5650328764B076A108EFF5fa7282a1B9aD2",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "USDS",
    "name": "Sky Dollar",
    "assetClass": "Crypto",
    "address": "0x2D88D75b625633dCcd65d9d53BfDD3Aea2d8e84f",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "USDT",
    "name": "Tether USD",
    "assetClass": "Crypto",
    "address": "0xbf3550B6fAe1671da7C238Af12e03Ac586BEf3B1",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "USO",
    "name": "United States Oil Fund LP ETF (Robinhood Tokenized ETF)",
    "assetClass": "Equity",
    "address": "0x75a9c76Ef439e2C7c2E5a34Ab105EcFe3766431c",
    "decimals": 8,
    "marketHours": "us_equities_24/5"
  },
  {
    "symbol": "WBTC",
    "name": "Wrapped Bitcoin",
    "assetClass": "Crypto",
    "address": "0x62107b0d3adA75fc1697fD342d99eed947a3aA5E",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "WEETH",
    "name": "Wrapped eETH",
    "assetClass": "Crypto",
    "address": "0xf882e1D50352aecB0Ac85378378918BCf40511e7",
    "decimals": 8,
    "marketHours": "Crypto"
  },
  {
    "symbol": "WSTETH",
    "name": "Wrapped stETH",
    "assetClass": "Crypto",
    "address": "0x3F5040B50FB37934573B210fE54B53a6F1A792E8",
    "decimals": 8,
    "marketHours": "Crypto"
  }
];

/** Look up a feed by proxy address (case-insensitive). */
export function feedByAddress(address: string): ChainlinkFeedInfo | undefined {
  const a = address.toLowerCase();
  return CHAINLINK_FEED_CATALOG.find((f) => f.address.toLowerCase() === a);
}

/** Look up a feed by ticker symbol, e.g. "NVDA", "SGOV", "ETH". */
export function feedBySymbol(symbol: string): ChainlinkFeedInfo | undefined {
  const s = symbol.toUpperCase();
  return CHAINLINK_FEED_CATALOG.find((f) => f.symbol === s);
}
