// AUTO-GENERATED by sdk/scripts/gen.mjs from Foundry build output — do not
// edit by hand. Regenerate with: forge build && pnpm --filter @novakoracle/sdk gen

import type { NovakDeployment } from "./types.js";

/** Known deployments keyed by chain ID (46630 = Robinhood Chain testnet, 31337 = local anvil). */
export const deployments: Record<number, NovakDeployment> = {
  "31337": {
    "chainId": 31337,
    "startBlock": 5,
    "deployedAt": "2026-10-05T22:48:55.651Z",
    "collateralIsMock": true,
    "collateral": "0x5fbdb2315678afecb367f032d93f642f64180aa3",
    "eventRegistry": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
    "eventComposer": "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
    "treasuryVault": "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
    "disputeManager": "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
    "eventBus": "0xa513e6e4b8f2a923d98304ec87f64353c4d5c853",
    "settlement": "0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6",
    "subscriptionManager": "0x8a791620dd6260079bf849dc5567adc3f2fdc318",
    "positionManager": "0x610178da211fef7d417bc0e6fed39f05609ad788",
    "market": "0xb7f8bc63bbcad18155201308c8f3540b07f84f5e",
    "distributionMarket": "0x0dcd1bf9a1b36ce34237eeafef220932846bcd82",
    "stockLendingGuard": "0x9a676e781a523b5d0c0e43731313a708cb607508"
  },
  "46630": {
    "chainId": 46630,
    "startBlock": 129498402,
    "deployedAt": "2026-10-05T22:39:02.795Z",
    "collateralIsMock": true,
    "collateral": "0xe90a7ffe1cbf704193a6635df0be70a756e523e6",
    "eventRegistry": "0x22699a7961a6538a7cea21c4636c1dc0f4cacc51",
    "eventComposer": "0x59e868fd1dc7a222613c52aac0e073ff89cfafb0",
    "treasuryVault": "0x765a4ba67c3c28b24806e94f395bc4e02708c6fb",
    "disputeManager": "0x632a4adc51dc1fae7b6895bfdd16bcb263ac82e7",
    "eventBus": "0x1e4537aff9f93a8d2dc90f8b56761dd6a358b32c",
    "settlement": "0x76ff164df1a3b6f032e7a3cf9dd5c0aa069851fd",
    "subscriptionManager": "0xbb579fd3ff188fd34d7da2da0b64e258bd2edfad",
    "positionManager": "0xed6bb54f0aa711859f2ecd108f59f97d667aadf2",
    "market": "0xd6efcb2e3e0f3ddf7951878847bc5422dc9a7d75",
    "distributionMarket": "0xc3af31add18d0d427a702516e92657c838c6b498",
    "stockLendingGuard": "0x530bd96cc480476506cdf97289a66b6587a928fb",
    "communityMarket": "0xb7bb0cf4c152679ac9aece7a8aba2fe0e41fa10c"
  }
};
