// AUTO-GENERATED by sdk/scripts/gen.mjs from Foundry build output — do not
// edit by hand. Regenerate with: forge build && pnpm --filter @novak/sdk gen

import type { NovakDeployment } from "./types.js";

/** Known deployments keyed by chain ID (46630 = Robinhood Chain testnet, 31337 = local anvil). */
export const deployments: Record<number, NovakDeployment> = {
  "31337": {
    "chainId": 31337,
    "startBlock": 6,
    "deployedAt": "2026-10-04T17:03:54.834Z",
    "collateralIsMock": true,
    "collateral": "0x5fbdb2315678afecb367f032d93f642f64180aa3",
    "eventRegistry": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
    "eventComposer": "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
    "treasuryVault": "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
    "disputeManager": "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
    "eventBus": "0xa513e6e4b8f2a923d98304ec87f64353c4d5c853",
    "settlement": "0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6",
    "subscriptionManager": "0x8a791620dd6260079bf849dc5567adc3f2fdc318",
    "positionManager": "0x610178da211fef7d417bc0e6fed39f05609ad788",
    "market": "0xb7f8bc63bbcad18155201308c8f3540b07f84f5e",
    "distributionMarket": "0x0dcd1bf9a1b36ce34237eeafef220932846bcd82",
    "stockLendingGuard": "0x9a676e781a523b5d0c0e43731313a708cb607508"
  },
  "46630": {
    "chainId": 46630,
    "startBlock": 128894045,
    "deployedAt": "2026-10-04T21:09:24.845Z",
    "collateralIsMock": true,
    "collateral": "0xc835601951cb8efc104ebf615510024dfe003f52",
    "eventRegistry": "0xb96f31bc07777f1f48de16533225f0964951e8f1",
    "eventComposer": "0x8ca95b815f1c6f732ed67d0880d672d7fbc33c2e",
    "treasuryVault": "0xf4dd6a333c66a765f1cb42e81ca2167b48217710",
    "disputeManager": "0xf9890adf5549bd39313e16ce7f5dc8c3aef48f63",
    "eventBus": "0xab30c697738007d5338bcdd7bb25353fddda1054",
    "settlement": "0x1336830154365ad443bd362a994cb4dabd9d583d",
    "subscriptionManager": "0x0b8b5b13ae378fa8a798a483e4fb5b22b4f35e9e",
    "positionManager": "0x95fe91f6762a4cd6487a62005194784190440ea7",
    "market": "0x73d5e83e5302019129efbf858955126db0deadad",
    "distributionMarket": "0xbfe9786dcc4bfd6c882159caa47367ac40d3ba94",
    "stockLendingGuard": "0x61a5a60887ecaedafbcb26c7b2b029b304ebb133"
  }
};
